name: 'JFrog Cli for Artifactory'
description: 'Runs various JFrog CLI Commands for artifactory'
inputs: 
  repoName: 
    description: "Name or artifactory repo where tools are stored"
    required: true
  remotePath:  
    description: 'Path in Artifactory repository to download'
    required: true
  destinationPath:
    description: "Local Path where file(s) will be downloaded"
    required: true
  limit:
    decription: "Maximum number of items to download"
    required: false
  flatten:
    decription: "Set to 'true' to flatten downloaded results to destination path and ignore soure directory hierarchy"
    required: false    
  sortBy:
    decription: "Set to 'true' to flatten downloaded results to destination path and ignore soure directory hierarchy"
    required: false
  sortOrder:
    decription: "The order by which fields in the 'sort-by' option should be sorted. Accepts 'asc' or 'desc'."
    required: true
    default: 'asc'
 
 
    
runs:
  using: "composite"
  steps:         
    - id: download       
      shell: bash
      run: |     
        downloadCommand="jfrog rt dl ${{ inputs.repoName }}/${{ inputs.remotePath }} ${{ inputs.destinationPath }} --sort-by=created --sort-order=desc"
        
        if [ -n "${{ inputs.limit }}" ]; then     
          downloadCommand="${downloadCommand} --limit=${{ inputs.limit }}"
        fi
        
        if [ -n "${{ inputs.flatten }}" ]; then     
          downloadCommand="${downloadCommand} --flat
        fi
        
        mkdir -p ${{ inputs.destinationPath }}
        echo "$downloadCommand"
        $downloadCommand
        ls  ${{ inputs.destinationPath }}/
        #jfrog rt dl ${{ inputs.repoName }}/${  inputs.remotePath }} ${{ inputs.destinationPath }} ${{ inputs.additionalArgs }}
        #--limit=1 --sort-by=created --sort-order=desc --flat --url=${{ env.ARTIFACTORY_URL }} --access-token=${{ env.JFROG_TOKEN }}
        

