name: 'JFrog Cli for Artifactory'
description: 'Runs various JFrog CLI Commands for artifactory'
inputs: 
  repoName: 
    description: "Name or artifactory repo where tools are stored"
    required: true
  remotePath:  
    description: 'Path in Artifactory repository to download'
    required: true
  destinationPath:
    description: "Local Path where file(s) will be downloaded"
    required: true
  limit:
    decription: "Maximum number of items to download"
    required: false
    
runs:
  using: "composite"
  steps:         
    - id: download       
      run: |
      shell: bash
        downloadCommand="jfrog rt dl ${{ inputs.repoName }}/${{ inputs.remotePath }} ${{ inputs.destinationPath }}"
        
        if [ -n "${{ inputs.limit }}" ]; then     
         downloadCommand="${downloadCommand} --limit=${{ inputs.limit }}"
        fi
        
        echo "$downloadCommand"
        $downloadCommand
        
        #jfrog rt dl ${{ inputs.repoName }}/${  inputs.remotePath }} ${{ inputs.destinationPath }} ${{ inputs.additionalArgs }}
        #--limit=1 --sort-by=created --sort-order=desc --flat --url=${{ env.ARTIFACTORY_URL }} --access-token=${{ env.JFROG_TOKEN }}
        

