name: 'Setup jfrog cli for Artifactory'
description: 'Download and configure JFrog CLI'
inputs:
  url:
    description: 'url for artifactory instance'
    required: true
    #default: '${{ env.ARTIFACTORY_URL }}'
  user: 
    description: 'url for artifactory instance'
    required: true
    #default: '${{ env.ARTIFACTORY_USERNAME }}'
  password: 
    description: 'url for artifactory instance'
    required: true
    #default: '${{ env.ARTIFACTORY_PASSWORD }}'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
   - name: Setup JFrog CLI
     uses: jfrog/setup-jfrog-cli@v2
  
   - name: checkInputs
     shell: bash
     run: |
      if [ -n "${{ inputs.url }}" ]; then
        echo "URL Provided, setting ARTIFACTORY_URL Environment Variable"
        echo "PSINT_ARTIFACTORY_URL=${{ inputs.url }}" >> $GITHUB_ENV;     
      else
         echo "URL NOT Provided, checking for previously set env variable"
         echo "PSINT_ARTIFACTORY_URL=${{ env.ARTIFACTORY_URL }}" >> $GITHUB_ENV;     
      fi
     
   - id: ConfigureCli
     name: Configure Jfrog Cli
     shell: bash
     run: |
        # Display Current JFrog Version
        jfrogversion=$(jfrog -v)
        IFS=' ' read -ra my_array <<< "$jfrogversion"
        echo "Using JFrog Version ${my_array[2]}"
        
        jfrog config show       
        
        # Configure JFrog Server
        jfrog config add --artifactory-url=${{ env.PSINT_ARTIFACTORY_URL }} --user=${{ env.PSINT_ARTIFACTORY_USERNAME }} --password=${{ env.PSINT_ARTIFACTORY_PASSWORD }}
        jfrog rt ping 
        jfrog config show 
      
    #- run: echo Hello ${{ inputs.who-to-greet }}.
    #  shell: bash
    #- id: random-number-generator
    #  run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #  shell: bash
    #- run: ${{ github.action_path }}/goodbye.sh
    #  shell: bash
